name: Daily Data Scraper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming requirements.txt is in the repository root
          pip install -r requirements.txt
          
      - name: Ensure output directory structure exists

        run: |
          mkdir -p ./data/gdeltdata/gdelt_portuguese_data

      - name: Run Arquivo Scraper and Log Progress

        run: python3 arquivo_scraper.py