# .github/workflows/scrape.yml
name: Scrape Ukraine War Data

on:
  # Run every hour
  schedule:
    - cron: '0 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      target:
        description: 'Number of articles to collect'
        required: false
        default: '50'

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Need to fetch full history to preserve data
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
          # Optional: pip install newspaper3k deep-translator langdetect
      
      - name: Run scraper
        run: |
          TARGET=${{ github.event.inputs.target || '50' }}
          python ukraine_war_scraper_improved.py \
            --out ukraine_war_data \
            --target $TARGET \
            --workers 3 \
            --max-requests 200
      
      - name: Check for new data
        id: check_data
        run: |
          if [ -d "ukraine_war_data" ]; then
            # Count JSON files
            FILE_COUNT=$(find ukraine_war_data -name "*.json" | wc -l)
            echo "file_count=$FILE_COUNT" >> $GITHUB_OUTPUT
            
            # Get data size
            DATA_SIZE=$(du -sh ukraine_war_data | cut -f1)
            echo "data_size=$DATA_SIZE" >> $GITHUB_OUTPUT
            
            if [ $FILE_COUNT -gt 0 ]; then
              echo "has_data=true" >> $GITHUB_OUTPUT
            else
              echo "has_data=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "has_data=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push data
        if: steps.check_data.outputs.has_data == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add ukraine_war_data/
          
          # Create commit with stats
          DATE=$(date -u +"%Y-%m-%d %H:%M UTC")
          FILES=${{ steps.check_data.outputs.file_count }}
          SIZE=${{ steps.check_data.outputs.data_size }}
          
          git diff --staged --quiet || git commit -m "Data collection: $DATE
          
          Files: $FILES
          Total size: $SIZE
          
          [skip ci]"
          
          git push
      
      - name: Upload artifacts (backup)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ukraine-war-data-${{ github.run_number }}
          path: ukraine_war_data/
          retention-days: 30

      - name: Create summary
        if: always()
        run: |
          echo "## Scraping Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Date**: $(date -u +"%Y-%m-%d %H:%M UTC")" >> $GITHUB_STEP_SUMMARY
          echo "- **Files**: ${{ steps.check_data.outputs.file_count }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Size**: ${{ steps.check_data.outputs.data_size }}" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "ukraine_war_data/progress.json" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Progress" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            cat ukraine_war_data/progress.json >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
